name: contact_api_parse
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.1.4

dependencies:
  contact_api:
    path: ../contact_api
  rxdart: ^0.27.7
  parse_server_sdk: ^6.2.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
