name: contact_auth_api_parse
description: Implementação da API de autenticação da aplicação de contatos
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.1.4

dependencies:
  contact_auth_api:
    path: ../contact_auth_api
  rxdart: ^0.27.7
  google_sign_in: ^6.1.5
  parse_server_sdk: ^6.2.0


dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
