name: contact_auth_api
description: Interfaces do módulo de autenticação da aplicação de contatos
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.1.4

dependencies:
  equatable: ^2.0.5

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
